require('dotenv').config()

const { PORT, DB_NAME, DB_USERNAME, DB_PASSWORD, DB_PORT, ACCESS_TOKEN_SECRET, DB_DIALEC, DB_HOST } = process.env

module.exports = { PORT, DB_NAME, DB_USERNAME, DB_PASSWORD, DB_PORT, ACCESS_TOKEN_SECRET, DB_DIALEC, DB_HOST }